name: Build docker release

on:
  release:
    types: [created]

jobs:
  release-docker:
    name: release docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set APP_VERSION env
        run: echo "APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev )" >> $GITHUB_ENV
      - name: Environment Printer
        uses: managedkaos/print-env@v1.0

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          tags: strider2038/goose-db-waiter:latest, strider2038/goose-db-waiter:${{ env.APP_VERSION }}
          pull: true
          push: true
          build-args: APP_VERSION=${{ env.APP_VERSION }}
